apiVersion: apps/v1
kind: Deployment
metadata:
  name: microposts-sample
  labels:
    app: microposts-sample
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microposts-sample
  template:
    metadata:
      labels:
        app: microposts-sample
    spec:
      containers:
        - name: microposts-sample
          image: microposts-sample
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: DATABASE_URL
              value: ecto://postgres:postgres@db-postgresql/postgres
            - name: SECRET_KEY_BASE
              value: mysecretmysecretmysecretmysecretmysecretmysecretmysecretmysecret
          ports:
            - containerPort: 4000
