apiVersion: v1
kind: Service
metadata:
  name: microposts-sample
  labels:
    app: microposts-sample
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 4000
      targetPort: 4000
  selector:
    app: microposts-sample
